name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes for testing
  # - cron: '0 21 * * 1-5' # Run M-F at 2100UTC (1700ET)

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch spy 
        uses: githubocto/flat@v3
        env:
          flat: ${{ secrets.flat }}
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=SPY&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8
          downloaded_filename: spy-hist.json
          postprocess: postprocess.js
      - name: Run postprocess.js on spy-hist.json
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js spy-hist.json
      - name: Fetch qqq 
        uses: githubocto/flat@v3
        env:
          flat: ${{ secrets.flat }}
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=QQQ&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8
          downloaded_filename: qqq-hist.json
          postprocess: postprocess.js
      - name: Run postprocess.js on qqq-hist.json
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js qqq-hist.json
      - name: Fetch sol 
        uses: githubocto/flat@v3
        env:
          flat: ${{ secrets.flat }}
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=SOLUSD&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8
          downloaded_filename: sol-hist.json
          postprocess: postprocess.js
      - name: Run postprocess.js on ssol-hist.json
        run: deno run -q --allow-read --allow-write --allow-run --allow-net --allow-env --unstable postprocess.js sol-hist.json
