name: Flat

on:
  push:
    paths:
      - .github/workflows/flat.yml
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes for testing
  # - cron: '0 21 * * 1-5' # Run M-F at 2100UTC (1700ET)

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Fetch spy 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=SPY&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8 # The data to fetch every 5 minutes
          downloaded_filename: spy-hist.json # The http_url gets saved and renamed in our repository as btc-price.json
          postprocess: postprocess.js # A postprocessing javascript or typescript file written in Deno
          # mask: true # optional param to mask the source http_url from the commit. Look at README for more options
      - name: Fetch qqq 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=QQQ&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8 # The data to fetch every 5 minutes
          downloaded_filename: qqq-hist.json # The http_url gets saved and renamed in our repository as btc-price.json
          postprocess: postprocess.js # A postprocessing javascript or typescript file written in Deno
          # mask: true # optional param to mask the source http_url from the commit. Look at README for more options
      - name: Fetch sol 
        uses: githubocto/flat@v3
        with:
          http_url: https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=SOLUSD&outputsize=compact&datatype=json&apikey=HJLDQLBSNDED5QR8 # The data to fetch every 5 minutes
          downloaded_filename: sol-hist.json # The http_url gets saved and renamed in our repository as btc-price.json
          postprocess: postprocess.js # A postprocessing javascript or typescript file written in Deno
          # mask: true # optional param to mask the source http_url from the commit. Look at README for more options
          
